config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  Rails.application.routes.draw do
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    devise_scope :user do
      get 'sign_out', to: 'devise/sessions#destroy', as: :delete_user_session
    end
    
    resources :comments
    resources :users

    resources :projects do
      resources :comments, commentable_type: 'Project'
    end

    root "projects#index"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body, :user

  belongs_to :commentable, polymorphic: true, counter_cache: :comments_count
  belongs_to :user

  delegate :full_name, :email, :image, to: :user, prefix: true
  delegate :name, to: :commentable, prefix: true
end

app/controllers/comments_controller.rb
class CommentsController < ProtectedController
  before_action :skip_policy_scope
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_commentable

  # GET /commentable/:commentable_id/comments
  # GET /commentable/:commentable_id/comments.json
  def index
    if @commentable.present?
      @comments = @commentable.comments.order(created_at: :desc)
    else
      @comments = Comment.all.order(created_at: :desc)  
    end  
  end

  # GET /comments/1
  def show
    authorize @comment
  end

  # GET /commentable/:commentable_id/new
  def new
    @comment = @commentable.comments.new
    authorize @comment
  end  

  def edit
    authorize @comment
  end  

  # POST /commentable/:commentable_id/comments
  # POST /commentable/:commentable_id/comments.json
  def create
    @comment = @commentable.comments.new(comment_params)  
    @comment.user = current_user
    authorize @comment

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: polymorphic_path([@commentable, @comment]) }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    authorize @comment 

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    authorize @comment
    @comment.destroy
    
    respond_to do |format|
      format.html { redirect_to comments_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_comment
      @comment = Comment.includes(:user, :commentable).find(params[:id])
    end

    # Only allow the white listed params through.
    def comment_params
      params.fetch(:comment, {}).permit(:body)
    end

    def set_commentable
      resource, id = request.path.split('/')[1,2]
      @commentable = resource.singularize.classify.constantize.find(id) if id.present?
    end
   
end  

app/views/comments/_comment.html.erb
<tr>
  <td><%= comment.id -%></td>
  <td><%= link_to comment.commentable_name, comment.commentable -%></td>
  <td><%= comment.user_full_name -%></td>
  <td><%= truncate(comment.body, length: 20) -%></td>
  <td><%= comment.created_at.to_s(:db) -%></td>
  
  <td class="text-right">
    <% if policy(comment).update? %>
      <%= link_to edit_comment_path(comment), class: 'btn btn-link btn-sm' do %>
        <i class="fa fa-edit" aria-hidden="true"></i> Edit
      <% end %>
    <% end %>
  
    <% if policy(comment).destroy? %>
      <%= link_to comment, {method: :delete, class: 'btn btn-link btn-sm', data: { confirm: 'Are you sure?' }} do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i> Destroy
      <% end %>
    <% end %>
  </td>
</tr>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <strong><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</strong>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="comment_body">Comment</label>
    <%= f.text_area :body, class: 'form-control', cols: 10, rows: 5 %>
  </div>

  <div class="form-group">
    <%= f.submit t('helpers.submit.submit', model: 'Comment'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <h3>Edit Comment</h3>

  <%= render 'form', comment: @comment %>  
</div> 

app/views/comments/index.html.erb
<div class="container">

  <h3>Comments</h3>  

  <% if @comments.size > 0 %>
    <table class="table table-striped table-hover table-sm mt-2">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Project</th>
          <th scope="col">Owner</th>
          <th scope="col">Comment</th>
          <th scope="col">Created At</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "comments/comment", collection: @comments %>       
      </tbody>
    </table> 
  <% else %>
    <p>No comments where found.</p>
  <% end %>

</div> 

app/views/comments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-md-9">
      <h2>New Comment</h2>

      <%= render 'form', commentable: @commentable, comment: @comment %>
    </div>
  </div>    
</div>  

app/views/comments/show.html.erb
<div class="media">
  <%= image_tag current_user.image, size: 40, alt: current_user.full_name, class: "rounded-circle" %>

  <div class="media-body"> 
    <h5 class="mt-0"><%= @comment.user_full_name -%></h5>
    <p><%= @comment.body -%></p>
  </div>
</div>