config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  Rails.application.routes.draw do
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    devise_scope :user do
      get 'sign_out', to: 'devise/sessions#destroy', as: :delete_user_session
    end
    
    resources :comments
    resources :users

    resources :projects do
      resources :comments, commentable_type: 'Project'
    end

    root "projects#index"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Commentable
  self.inheritance_column = "project_type"
  
  belongs_to :owner, class_name: "User"

  enum status: [ :created, :started, :stopped, :completed ]
  enum type: [ :public, :private ], _suffix: :project

  delegate :full_name, to: :owner, prefix: true

  validates_presence_of :name, :type, :estimated_effort_level
end  

app/controllers/projects_controller.rb
class ProjectsController < ProtectedController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = policy_scope(Project).order(created_at: :desc)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize @project
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.owner = current_user
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project  

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project  
    @project.destroy
    
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.includes(:comments, :owner).find(params[:id])
    end

    # Only allow the white listed params through.
    def project_params
      params.fetch(:project, {}).permit(
        :name, :description, :status, :type, :estimated_effort_level, :actual_effort_level
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def project_type_badge(type)
    if type == "private"
      badge_class = "danger"
    else
      badge_class = "success"
    end    

    content_tag(:span, type, class: ['badge', "badge-#{badge_class}"])  
  end  

  # Assigns a bootstrap badge class to the project status
  def project_status_badge(status)
    badge_class =
      case status
        when 'created' then 'primary' 
        when 'stopped' then 'danger'
        else 'success'       
      end
          
    content_tag(:span, status, class: ['badge', "badge-#{badge_class}"])
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <strong><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</strong>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="project_name">Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>  

  <div class="form-group">
    <label for="project_description">Description</label>
    <%= f.text_area :description, class: 'form-control', cols: 10, rows: 5 %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <label for="project_type">Type</label>
        <%= f.select(:type, Project.types.map{|t| [t[0], t[0]]}, {}, {id: 'project_type', class: 'form-control col-sm-4'} ) %>
      </div> 

      <% if project.persisted? %>
        <div class="form-group">
          <label for="project_status">Status</label>
          <%= f.select(:status, Project.statuses.map{|t| [t[0], t[0]]}, {}, {id: 'project_status', class: 'form-control col-sm-4'} ) %>
        </div> 
      <% end %>    
    </div>
    <div class="col-6">
      <div class="form-group">
        <label for="estimated_effort_level">Estimated Effort Level (Hours)</label>
        <%= f.number_field :estimated_effort_level, class: 'form-control col-sm-4' %>
      </div>

      <% if project.persisted? %>
        <div class="form-group">
          <label for="actual_effort_level">Actual Effort Level (Hours)</label>
          <%= f.number_field :actual_effort_level, class: 'form-control col-sm-4' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit t('helpers.submit.submit', model: 'Project'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="card card-project">
  <div class="card-header">
    <div class="row">
      <div class="col-7">
        <h1><%= project.name -%></h1>
      </div>
      <div class="col-5"> 
        <span class="project-status project-status-<%= project.status -%>"><%= project.status -%></span>
      </div>
    </div>
  </div>
  <div class="card-block">
    <div class="row">
      <div class="col-12">
        <ul class="list-inline">
          <li class="list-inline-item"><i class="fa fa-user"></i> <a href="#"><%= project.owner_full_name -%></a></li>
          <li class="list-inline-item"><i class="fa fa-clock-o"></i> <%= link_to "#{time_ago_in_words(project.created_at)} ago", project -%></a></li>
        </ul>
      </div>
    </div>

    <div class="row">      
      <div class="col-md-7 col-12">
        <div class="card-text mb-4"><%= project.description -%></div>
      </div>

      <div class="col-md-5 col-12">        
        <div class="row no-gutters">
          <div class="col-6 col-md-6 card card-level card-level-left mb-0">
            <div class="card-header">
              <span>Estimated level of effort</span>
            </div>
            <div class="card-block">
              <span><%= project.estimated_effort_level.to_i -%></span>
            </div>
          </div>
  
          <div class="col-6 col-md-6 card card-level card-level-right mb-0">
            <div class="card-header active">
              <span>Actual level of effort</span>
            </div>
            <div class="card-block active">
              <span><%= project.actual_effort_level.to_i -%></span>
            </div>
          </div> 
        </div>  
      </div>
    </div>
  </div>
</div>

<!--
<tr>
  <td><%= project.id -%></td>
  <td><%= link_to project.name, project -%></td>
  <td><%= project_type_badge(project.type) -%></td>
  <td><%= project.owner_full_name -%></td>
  <td><%= project_status_badge(project.status) -%></td>
  <td><%= link_to project.comments_count, project_comments_path(project) -%></td>
  <td><%= project.created_at.to_s(:db) -%></td>
  <td class="text-right">
    <% if policy(project).update? %>
      <%= link_to edit_project_path(project), class: 'btn btn-link btn-sm' do %>
        <i class="fa fa-edit" aria-hidden="true"></i> Edit
      <% end %>
    <% end %>
  
    <% if policy(project).destroy? %>
      <%= link_to project, {method: :delete, class: 'btn btn-link btn-sm', data: { confirm: 'Are you sure?' }} do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i> Destroy
      <% end %>
    <% end %>
  </td>
</tr>
-->

app/views/projects/edit.html.erb
<div class="container">
  <h3>Edit Project <%= @project.name -%></h3>
  <%= render 'form', project: @project %>  
</div>  

app/views/projects/index.html.erb
<div class="container">
  
  <!--
  <div class="row">
    <div class="col-6">
      <h3>Projects</h3>
    </div>
    <div class="col-6 text-right">
      <%= link_to(new_project_path, class: 'btn btn-outline-primary') do %>
        <i class="fa fa-plus" aria-hidden="true"></i> Add Project
      <% end %> 
    </div>
  </div>
  -->

  <% if @projects.size > 0 %>
    <%= render @projects %>
    <!--
    <table class="table table-striped table-hover table-sm mt-2">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Type</th>
          <th scope="col">Owner</th>
          <th scope="col">Status</th>
          <th scope="col">Comments</th>
          <th scope="col">Created At</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <%#= render @projects %>       
      </tbody>
    </table> 
    -->
  <% else %>
    <p>No projects where found.</p>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h3>New Project</h3>
  <%= render 'form', project: @project %>
</div>  

app/views/projects/show.html.erb
<div class="container">
  
  <div class="row mb-2">
    <div class="col-6">
      <h3><%= @project.name -%></h3>
    </div>
    <div class="col-6 text-right">
      <% if policy(@project).update? %>
        <%= link_to(edit_project_path(@project), class: 'btn btn-outline-primary') do %>
          <i class="fa fa-edit" aria-hidden="true"></i> Edit Project
        <% end %> 
      <% end %>
    </div>
  </div>
  
  <div class="row mb-2">
    <div class="col-4"><strong>Type</strong></div>
    <div class="col-8"><%= project_type_badge(@project.type) -%></div>
  </div>

  <div class="row mb-2">
    <div class="col-4"><strong>Status</strong></div>
    <div class="col-8"><%= project_status_badge(@project.status) -%></div>
  </div>
 
  <div class="row mb-2">
    <div class="col-4"><strong>Description</strong></div>
    <div class="col-8"><%= @project.description -%></div>
  </div>

  <div class="row mb-2">
    <div class="col-4"><strong>Estimated Effort Level (Hours)</strong></div>
    <div class="col-8"><%= @project.estimated_effort_level -%></div>
  </div>

  <div class="row mb-2">
    <div class="col-4"><strong>Actual Effort Level (Hours)</strong></div>
    <div class="col-8"><%= @project.actual_effort_level -%></div>
  </div>

  <div class="row mb-2">
    <div class="col-4"><strong>Created By</strong></div>
    <div class="col-8"><%= @project.owner_full_name -%></div>
  </div>

  <div class="row mb-2">
    <div class="col-4"><strong>Created At</strong></div>
    <div class="col-8"><%= @project.created_at -%></div>
  </div>

   <div class="row mb-2">
    <div class="col-4"><strong>Updated At</strong></div>
    <div class="col-8"><%= @project.updated_at -%></div>
  </div>

  <div class="row">
    <div class="col-12">
       <%= react_component('ThreadList', resourceUrl: project_comments_url(@project, format: 'json'), imageSize: 40, threadCount: @project.comments_count, placeholder: "Add a public comment...") %>
    </div>
  </div>
</div> 