config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  Rails.application.routes.draw do
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    devise_scope :user do
      get 'sign_out', to: 'devise/sessions#destroy', as: :delete_user_session
    end
    
    resources :comments
    resources :users

    resources :projects do
      resources :comments, commentable_type: 'Project'
    end

    root "projects#index"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_alert_class_for(flash_type)    
    case flash_type.to_sym
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :notice
        "alert-info"
      else
        "alert-info"
    end
  end

  def nav_item_state_for(resource)
    controller_name == resource ? "active" : ""
  end  
end

app/views/layouts/application/_authenticated_menu.html.erb
<ul class="navbar-nav mr-auto"> 
  <li class="nav-item <%= nav_item_state_for('projects') -%>">
    <%= link_to "Projects", projects_path, class: 'nav-link' if policy(Project).index? %>
  </li> 
  <li class="nav-item <%= nav_item_state_for('admin_comments') -%>">
    <%= link_to "Comments", comments_path, class: 'nav-link' if policy(Comment).index? %>
  </li>
  <li class="nav-item <%= nav_item_state_for('users') -%>">
    <%= link_to "Users", users_path, class: 'nav-link' if policy(User).index? %>
  </li>
</ul>

app/views/layouts/application/_header.html.erb
<!-- header.html -->
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#mainNav" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to "Home Improvement", root_path, class: 'navbar-brand' %>
  
  <% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="mainNav">  
    <%= link_to "New Project", new_project_path, class: 'btn btn-danger' %>
    <%= render "layouts/application/authenticated_menu" %> 
    <%= link_to "Sign Out", delete_user_session_path, class: "btn btn-primary" %>
    <%# render "layouts/application/user_menu" %>    
  </div>
  <% end %>
</nav>
<!-- header.html -->

app/views/layouts/application/_user_menu.html.erb
<!-- _user_menu.html -->
<div class="dropdown">      
  <button class="btn dropdown-toggle dropdown-image-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag current_user.image || "", size: 30, alt: current_user.full_name, class: "rounded-circle" %>
  </button>

  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownAuthMenu">
    <a class="dropdown-item" href="<%= delete_user_session_path -%>">Log Out</a>
  </div>
</div>
<!-- _user_menu.html -->